# Generated by Django 5.2.13 on 2026-04-29 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'mechanic'}, on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_mechanics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mechanicservice',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='marketplace.mechanicprofile'),
        ),
    ]
