# Generated by Django 5.2.13 on 2026-04-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FLAT', 'Flat Fee')], default='PERCENTAGE', max_length=20)),
                ('fee_value', models.DecimalField(decimal_places=2, default=10.0, help_text='e.g., 10.00 for 10% or $10', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Configuration',
                'verbose_name_plural': 'Platform Configurations',
            },
        ),
    ]
