# Generated by Django 5.2.13 on 2026-05-11 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default='', help_text='A friendly name, e.g. "My Daily Ride"', max_length=100)),
                ('brand', models.CharField(help_text='e.g. Honda, Yamaha, Royal Enfield', max_length=100)),
                ('model', models.CharField(help_text='e.g. Activa 6G, R15 V4', max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Manufacturing year', null=True)),
                ('registration_no', models.CharField(blank=True, default='', help_text='e.g. KA-01-AB-1234', max_length=30)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('engine_cc', models.PositiveIntegerField(blank=True, help_text='Engine displacement in cc', null=True)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric')], default='PETROL', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bikes/')),
                ('notes', models.TextField(blank=True, default='', help_text='Private notes for the owner')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
