# Generated by Django 5.2.13 on 2026-05-11 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
        ('bookings', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bike',
            field=models.ForeignKey(blank=True, help_text='Registered bike for this service (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bikes.bike'),
        ),
    ]
